In [9]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.int16)
B = np.array([
    [1, 2],
    [7, 8],
    [10, 10]
])

C = np.dot(A, B)
D = np.array([
    [2, 1],
    [8, 7],
    [10, 10]
])
B - D

array([[-1,  1],
       [-1,  1],
       [ 0,  0]])

In [10]:
B.T

array([[ 1,  7, 10],
       [ 2,  8, 10]])

In [13]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [17]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
np.linalg.inv(M)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [20]:
X = np.array([
    [23, 0.5, 1],
    [35, 1, 1],
    [18, 0, 1]
])

Y = np.array([55, 100, 45])

In [21]:
xxt = np.dot(X.T, X)

In [22]:
xxt_inv = np.linalg.inv(xxt)

In [23]:
xxt_inv

array([[ 0.12244898, -2.08163265, -2.06122449],
       [-2.08163265, 37.3877551 , 34.04081633],
       [-2.06122449, 34.04081633, 35.53061224]])

In [25]:
xxt_inv_xt = np.dot(xxt_inv, X.T)

In [26]:
final_betas = np.dot(xxt_inv_xt, Y)

In [27]:
final_betas

array([  5., -30., -45.])