In [2]:
# !pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

In [3]:
import torch
import numpy as np

In [4]:
shape = (3, 2, 2)

tensor = torch.ones(shape)
tensor = torch.zeros(shape)
tensor = torch.empty(shape)
tensor = torch.rand(shape)
tensor

tensor([[[0.0958, 0.3230],
         [0.6941, 0.9544]],

        [[0.6729, 0.4108],
         [0.7302, 0.4964]],

        [[0.2693, 0.1261],
         [0.7021, 0.8818]]])

In [5]:
np_arr = np.array(tensor)
tensor_2 = torch.from_numpy(np_arr) 
print(np_arr)
print('------------')
print(tensor_2)

[[[0.09575045 0.3229525 ]
  [0.6940878  0.95442945]]

 [[0.67290777 0.41075027]
  [0.73020303 0.4964257 ]]

 [[0.26930684 0.12609595]
  [0.70207447 0.8818126 ]]]
------------
tensor([[[0.0958, 0.3230],
         [0.6941, 0.9544]],

        [[0.6729, 0.4108],
         [0.7302, 0.4964]],

        [[0.2693, 0.1261],
         [0.7021, 0.8818]]])


C:\Users\jackt\AppData\Local\Temp\ipykernel_21236\3200783129.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np_arr = np.array(tensor)


### Создадим тензор изображения

In [6]:
image_shape = (3, 9, 16)

image_tensor = torch.rand(image_shape)
image_tensor

tensor([[[2.8542e-01, 1.4252e-01, 5.2155e-01, 4.4973e-01, 2.4623e-01,
          1.1510e-01, 5.6082e-01, 4.4173e-01, 5.8880e-01, 2.0263e-01,
          7.9153e-01, 7.0569e-01, 4.6837e-01, 1.1695e-02, 8.7197e-02,
          7.6234e-01],
         [5.0062e-02, 7.8056e-01, 7.5334e-02, 6.8862e-01, 1.3371e-01,
          7.1677e-01, 9.8661e-01, 3.7357e-01, 9.7726e-01, 1.9361e-01,
          8.0073e-01, 5.5059e-01, 7.9738e-01, 7.3882e-01, 5.8417e-01,
          2.0982e-01],
         [2.3433e-01, 6.6203e-02, 9.7650e-03, 5.7265e-01, 4.3228e-01,
          4.4532e-01, 1.0783e-01, 5.8918e-01, 8.4357e-01, 2.7487e-01,
          7.9959e-01, 3.8966e-02, 7.0354e-02, 6.9773e-01, 5.4895e-01,
          3.7147e-01],
         [4.7629e-01, 5.2581e-01, 1.1869e-01, 3.9755e-01, 7.0374e-01,
          4.1105e-01, 9.5673e-02, 1.8862e-01, 5.4938e-01, 4.4070e-01,
          6.9207e-02, 4.4036e-01, 9.6548e-01, 4.4645e-01, 6.3422e-03,
          9.7365e-01],
         [2.4067e-01, 7.8716e-01, 5.5663e-01, 9.6512e-01, 7.5493e-01

In [7]:
image_tensor.ravel()

tensor([2.8542e-01, 1.4252e-01, 5.2155e-01, 4.4973e-01, 2.4623e-01, 1.1510e-01,
        5.6082e-01, 4.4173e-01, 5.8880e-01, 2.0263e-01, 7.9153e-01, 7.0569e-01,
        4.6837e-01, 1.1695e-02, 8.7197e-02, 7.6234e-01, 5.0062e-02, 7.8056e-01,
        7.5334e-02, 6.8862e-01, 1.3371e-01, 7.1677e-01, 9.8661e-01, 3.7357e-01,
        9.7726e-01, 1.9361e-01, 8.0073e-01, 5.5059e-01, 7.9738e-01, 7.3882e-01,
        5.8417e-01, 2.0982e-01, 2.3433e-01, 6.6203e-02, 9.7650e-03, 5.7265e-01,
        4.3228e-01, 4.4532e-01, 1.0783e-01, 5.8918e-01, 8.4357e-01, 2.7487e-01,
        7.9959e-01, 3.8966e-02, 7.0354e-02, 6.9773e-01, 5.4895e-01, 3.7147e-01,
        4.7629e-01, 5.2581e-01, 1.1869e-01, 3.9755e-01, 7.0374e-01, 4.1105e-01,
        9.5673e-02, 1.8862e-01, 5.4938e-01, 4.4070e-01, 6.9207e-02, 4.4036e-01,
        9.6548e-01, 4.4645e-01, 6.3422e-03, 9.7365e-01, 2.4067e-01, 7.8716e-01,
        5.5663e-01, 9.6512e-01, 7.5493e-01, 6.9089e-01, 6.9164e-01, 9.4838e-01,
        8.0102e-01, 6.8267e-01, 5.7608e-

In [8]:
image_tensor.ravel().shape

torch.Size([432])

In [9]:
3*9*16

432

In [10]:
# посчитать число элементов тензора любой размерности
image_tensor.numel()

432

In [11]:
image_tensor.reshape(3, 9*16)

tensor([[2.8542e-01, 1.4252e-01, 5.2155e-01, 4.4973e-01, 2.4623e-01, 1.1510e-01,
         5.6082e-01, 4.4173e-01, 5.8880e-01, 2.0263e-01, 7.9153e-01, 7.0569e-01,
         4.6837e-01, 1.1695e-02, 8.7197e-02, 7.6234e-01, 5.0062e-02, 7.8056e-01,
         7.5334e-02, 6.8862e-01, 1.3371e-01, 7.1677e-01, 9.8661e-01, 3.7357e-01,
         9.7726e-01, 1.9361e-01, 8.0073e-01, 5.5059e-01, 7.9738e-01, 7.3882e-01,
         5.8417e-01, 2.0982e-01, 2.3433e-01, 6.6203e-02, 9.7650e-03, 5.7265e-01,
         4.3228e-01, 4.4532e-01, 1.0783e-01, 5.8918e-01, 8.4357e-01, 2.7487e-01,
         7.9959e-01, 3.8966e-02, 7.0354e-02, 6.9773e-01, 5.4895e-01, 3.7147e-01,
         4.7629e-01, 5.2581e-01, 1.1869e-01, 3.9755e-01, 7.0374e-01, 4.1105e-01,
         9.5673e-02, 1.8862e-01, 5.4938e-01, 4.4070e-01, 6.9207e-02, 4.4036e-01,
         9.6548e-01, 4.4645e-01, 6.3422e-03, 9.7365e-01, 2.4067e-01, 7.8716e-01,
         5.5663e-01, 9.6512e-01, 7.5493e-01, 6.9089e-01, 6.9164e-01, 9.4838e-01,
         8.0102e-01, 6.8267e

### Собираем несколько тензоров в один

In [12]:
x = torch.rand(2, 3)
x

tensor([[0.5333, 0.6492, 0.5572],
        [0.4272, 0.9187, 0.8449]])

In [13]:
torch.cat((x,x,x), dim = 0)

tensor([[0.5333, 0.6492, 0.5572],
        [0.4272, 0.9187, 0.8449],
        [0.5333, 0.6492, 0.5572],
        [0.4272, 0.9187, 0.8449],
        [0.5333, 0.6492, 0.5572],
        [0.4272, 0.9187, 0.8449]])

In [14]:
torch.cat((x,x,x), dim = 1)

tensor([[0.5333, 0.6492, 0.5572, 0.5333, 0.6492, 0.5572, 0.5333, 0.6492, 0.5572],
        [0.4272, 0.9187, 0.8449, 0.4272, 0.9187, 0.8449, 0.4272, 0.9187, 0.8449]])

In [15]:
x = torch.rand(1, 3)
y = torch.rand(5, 3)
z = torch.rand(3, 3)

for tensor in [x, y, z]:
    print(tensor, end = '\n\n')

print(torch.cat((x, y, z), dim = 0))

tensor([[0.1086, 0.7658, 0.8604]])

tensor([[0.6313, 0.7388, 0.7972],
        [0.3406, 0.4876, 0.7639],
        [0.4774, 0.1022, 0.9995],
        [0.6251, 0.7358, 0.1966],
        [0.4202, 0.4384, 0.3624]])

tensor([[0.1706, 0.2350, 0.1674],
        [0.8105, 0.5539, 0.0176],
        [0.4206, 0.8078, 0.8486]])

tensor([[0.1086, 0.7658, 0.8604],
        [0.6313, 0.7388, 0.7972],
        [0.3406, 0.4876, 0.7639],
        [0.4774, 0.1022, 0.9995],
        [0.6251, 0.7358, 0.1966],
        [0.4202, 0.4384, 0.3624],
        [0.1706, 0.2350, 0.1674],
        [0.8105, 0.5539, 0.0176],
        [0.4206, 0.8078, 0.8486]])


### Добавляем дополнительную ось

In [16]:
x = torch.rand(2, 3)
print(x)
print()
print(x.unsqueeze(0), x.unsqueeze(0).shape)
print()
print(x.unsqueeze(1), x.unsqueeze(1).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(2).shape)


tensor([[0.3313, 0.7446, 0.2783],
        [0.5277, 0.2482, 0.9556]])

tensor([[[0.3313, 0.7446, 0.2783],
         [0.5277, 0.2482, 0.9556]]]) torch.Size([1, 2, 3])

tensor([[[0.3313, 0.7446, 0.2783]],

        [[0.5277, 0.2482, 0.9556]]]) torch.Size([2, 1, 3])

tensor([[[0.3313],
         [0.7446],
         [0.2783]],

        [[0.5277],
         [0.2482],
         [0.9556]]]) torch.Size([2, 3, 1])


### Уберем оси, где размерность - 1

In [17]:
x = torch.rand(1, 2, 1, 3)

print(x)
print()
print(x.squeeze(), x.squeeze().shape)
print()
# уберем нулевую ось, у нее должна быть размерность - 1 !
print(x.squeeze(0), x.squeeze(0).shape)

tensor([[[[0.2538, 0.7405, 0.1705]],

         [[0.7447, 0.1257, 0.8431]]]])

tensor([[0.2538, 0.7405, 0.1705],
        [0.7447, 0.1257, 0.8431]]) torch.Size([2, 3])

tensor([[[0.2538, 0.7405, 0.1705]],

        [[0.7447, 0.1257, 0.8431]]]) torch.Size([2, 1, 3])


### Проверим, доступна ли видеокарта

In [18]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())

False


AssertionError: Torch not compiled with CUDA enabled

In [19]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

print(device)

cpu


In [23]:
tensor = torch.tensor([1, 250, 33, 1], device = device)
print(tensor.to(device))
print(tensor.to(torch.int16))

tensor([  1, 250,  33,   1])
tensor([  1, 250,  33,   1], dtype=torch.int16)


### Операции с матрицами

In [24]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)

tensor([[0.8473, 0.8981, 0.1446],
        [0.6134, 0.9073, 0.5193]])
tensor([[0.0825, 0.3819, 0.3165],
        [0.4432, 0.7533, 0.4893]])


In [26]:
# сложение
print(a+b)
print()
print(torch.add(a, b))
print()
print(a.add(b))

tensor([[0.9298, 1.2800, 0.4611],
        [1.0565, 1.6606, 1.0086]])

tensor([[0.9298, 1.2800, 0.4611],
        [1.0565, 1.6606, 1.0086]])

tensor([[0.9298, 1.2800, 0.4611],
        [1.0565, 1.6606, 1.0086]])


In [27]:
# вычитание
print(a-b)
print()
print(torch.sub(a, b))
print()
print(a.sub(b))

tensor([[ 0.7648,  0.5162, -0.1719],
        [ 0.1702,  0.1540,  0.0300]])

tensor([[ 0.7648,  0.5162, -0.1719],
        [ 0.1702,  0.1540,  0.0300]])

tensor([[ 0.7648,  0.5162, -0.1719],
        [ 0.1702,  0.1540,  0.0300]])


In [28]:
# умножение
print(a*b)
print()
print(torch.mul(a, b))
print()
print(a.mul(b))

tensor([[0.0699, 0.3430, 0.0458],
        [0.2718, 0.6835, 0.2541]])

tensor([[0.0699, 0.3430, 0.0458],
        [0.2718, 0.6835, 0.2541]])

tensor([[0.0699, 0.3430, 0.0458],
        [0.2718, 0.6835, 0.2541]])


In [29]:
# деление
print(a/b)
print()
print(torch.div(a, b))
print()
print(a.div(b))

tensor([[10.2685,  2.3516,  0.4568],
        [ 1.3841,  1.2044,  1.0613]])

tensor([[10.2685,  2.3516,  0.4568],
        [ 1.3841,  1.2044,  1.0613]])

tensor([[10.2685,  2.3516,  0.4568],
        [ 1.3841,  1.2044,  1.0613]])


In [30]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)
c = torch.rand(5, 5)
a, b, c

(tensor([[0.7688, 0.5502, 0.3120],
         [0.6895, 0.5214, 0.9708]]),
 tensor([[0.7731, 0.0823, 0.4236, 0.2650],
         [0.3807, 0.2284, 0.3896, 0.4191],
         [0.2648, 0.9065, 0.3187, 0.0337]]),
 tensor([[0.8707, 0.1923, 0.6166, 0.2403, 0.0594],
         [0.5744, 0.1432, 0.3620, 0.4353, 0.2368],
         [0.3083, 0.2315, 0.3451, 0.9671, 0.4104],
         [0.8745, 0.1750, 0.5117, 0.7142, 0.1924],
         [0.9877, 0.6759, 0.3714, 0.2802, 0.3967]]))

#### матричные операции

In [34]:
print(a @ b, (a@b).shape)
print()
print(torch.matmul(a, b), torch.matmul(a, b).shape)
print()
print(c.trace())
print()
print(c.exp())

tensor([[0.8864, 0.4718, 0.6395, 0.4449],
        [0.9886, 1.0559, 0.8046, 0.4340]]) torch.Size([2, 4])

tensor([[0.8864, 0.4718, 0.6395, 0.4449],
        [0.9886, 1.0559, 0.8046, 0.4340]]) torch.Size([2, 4])

tensor(2.4699)

tensor([[2.3885, 1.2121, 1.8525, 1.2716, 1.0612],
        [1.7761, 1.1540, 1.4363, 1.5455, 1.2671],
        [1.3611, 1.2605, 1.4121, 2.6304, 1.5074],
        [2.3976, 1.1912, 1.6681, 2.0425, 1.2122],
        [2.6851, 1.9659, 1.4498, 1.3234, 1.4870]])


#### Автоматическое дифференцирование

In [37]:
# исходные признаки
x = torch.rand( 5)
x

tensor([0.3167, 0.9508, 0.6229, 0.2339, 0.2476])

In [38]:
# веса трех моделей: z1,z2,z3
w = torch.rand(3, 5, requires_grad = True)

w

tensor([[0.0752, 0.1437, 0.6462, 0.0018, 0.2652],
        [0.1468, 0.0514, 0.2437, 0.0814, 0.3530],
        [0.6626, 0.5552, 0.4482, 0.0192, 0.0731]], requires_grad=True)

In [40]:
print(w.grad)

None


In [45]:
first_z = torch.zeros(3)

first_z

tensor([0., 0., 0.])

In [46]:
# получаем результаты трех моделей по признакам (предикты)
for i in range(3):
    print(w[i])
    first_z[i] = torch.sum(w[i]*x)
first_z

tensor([0.0752, 0.1437, 0.6462, 0.0018, 0.2652], grad_fn=<SelectBackward0>)
tensor([0.1468, 0.0514, 0.2437, 0.0814, 0.3530], grad_fn=<SelectBackward0>)
tensor([0.6626, 0.5552, 0.4482, 0.0192, 0.0731], grad_fn=<SelectBackward0>)


tensor([0.6290, 0.3536, 1.0395], grad_fn=<CopySlices>)

In [47]:
second_z = torch.matmul(x, w.t())
second_z

tensor([0.6290, 0.3536, 1.0395], grad_fn=<SqueezeBackward4>)

In [48]:
# веса итоговой модели
v = torch.rand(3, requires_grad = True)

v

tensor([0.4546, 0.2897, 0.0994], requires_grad=True)

In [50]:
# получаем результат второго слоя
y = torch.sum(second_z * v)
y

tensor(0.4917, grad_fn=<SumBackward0>)

In [51]:
y.item()

0.49170738458633423

#### Посчитаем ошибку

In [52]:
loss = torch.mean((y-2)**2)

In [53]:
loss

tensor(2.2749, grad_fn=<MeanBackward0>)

In [54]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z.grad=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=None

z.grad=None

v.grad=None



In [55]:
loss.backward()

In [56]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z.grad=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=tensor([[-0.4343, -1.3039, -0.8542, -0.3208, -0.3395],
        [-0.2768, -0.8309, -0.5443, -0.2044, -0.2163],
        [-0.0950, -0.2851, -0.1868, -0.0701, -0.0742]])

z.grad=None

v.grad=tensor([-1.8975, -1.0667, -3.1357])



#### Сделаем шаг градиентного спуска на простом примере

In [57]:
a = torch.rand(1, requires_grad = True)
b = torch.rand(1, requires_grad = True)
a, b

(tensor([0.5683], requires_grad=True), tensor([0.6039], requires_grad=True))

In [58]:
loss = (a-b)
loss

tensor([-0.0356], grad_fn=<SubBackward0>)

In [59]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [65]:
loss.backward()

In [66]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([2.])

b.grad=tensor([-2.])



In [68]:
# при шаге градиентного спуска, градиент в конце нужно занулять, чтобы значения не суммировались
a.grad.zero_()
b.grad.zero_()

tensor([0.])

In [69]:
loss = (a-b)**2
loss

tensor([0.0013], grad_fn=<PowBackward0>)

In [70]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([0.])

b.grad=tensor([0.])



In [71]:
loss.backward()

In [72]:
print(f'{a.grad=}\n') # 2 * (a-b) 
print(f'{b.grad=}\n') # -2 * (a-b)

a.grad=tensor([-0.0712])

b.grad=tensor([0.0712])



#### Сделаем матрицы побольше

In [73]:
a = torch.rand(3, 5, requires_grad = True)
b = torch.rand(3, 5, requires_grad = True)
a, b

(tensor([[0.2731, 0.5557, 0.6598, 0.6281, 0.9227],
         [0.3479, 0.7241, 0.0538, 0.6333, 0.4262],
         [0.6166, 0.2731, 0.8915, 0.5509, 0.4422]], requires_grad=True),
 tensor([[0.6736, 0.9952, 0.5138, 0.8595, 0.5640],
         [0.7257, 0.3743, 0.7703, 0.1194, 0.4589],
         [0.8635, 0.9862, 0.8922, 0.1079, 0.5119]], requires_grad=True))

In [75]:
loss = torch.mean(a * b)
loss

tensor(0.3237, grad_fn=<MeanBackward0>)

In [76]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [77]:
loss.backward()

In [78]:
print(f'{a.grad=}\n') # b / (3*5)
print(f'{b.grad=}\n') # a / (3*5)

a.grad=tensor([[0.0449, 0.0663, 0.0343, 0.0573, 0.0376],
        [0.0484, 0.0250, 0.0514, 0.0080, 0.0306],
        [0.0576, 0.0657, 0.0595, 0.0072, 0.0341]])

b.grad=tensor([[0.0182, 0.0370, 0.0440, 0.0419, 0.0615],
        [0.0232, 0.0483, 0.0036, 0.0422, 0.0284],
        [0.0411, 0.0182, 0.0594, 0.0367, 0.0295]])



In [82]:
a/15

tensor([[0.0182, 0.0370, 0.0440, 0.0419, 0.0615],
        [0.0232, 0.0483, 0.0036, 0.0422, 0.0284],
        [0.0411, 0.0182, 0.0594, 0.0367, 0.0295]], grad_fn=<DivBackward0>)

In [80]:
b/15

tensor([[0.0449, 0.0663, 0.0343, 0.0573, 0.0376],
        [0.0484, 0.0250, 0.0514, 0.0080, 0.0306],
        [0.0576, 0.0657, 0.0595, 0.0072, 0.0341]], grad_fn=<DivBackward0>)

#### Посчитаем 2 разных лосса

In [85]:
a = torch.rand(3, 5, requires_grad = True)

print(f'{a=}\n')

loss1 = torch.sum(a ** 2) # 2*a
loss2 = torch.sum(a) # 1

print(f'{a.grad=}\n')

loss1.backward()

print(f'{a.grad=}\n')

loss2.backward()

print(f'{a.grad=}\n')

a=tensor([[0.0407, 0.1293, 0.8978, 0.2885, 0.5918],
        [0.9784, 0.5767, 0.0034, 0.1299, 0.7297],
        [0.7800, 0.2392, 0.3818, 0.8095, 0.5271]], requires_grad=True)

a.grad=None

a.grad=tensor([[0.0814, 0.2586, 1.7956, 0.5771, 1.1836],
        [1.9568, 1.1533, 0.0067, 0.2598, 1.4594],
        [1.5600, 0.4783, 0.7635, 1.6191, 1.0542]])

a.grad=tensor([[1.0814, 1.2586, 2.7956, 1.5771, 2.1836],
        [2.9568, 2.1533, 1.0067, 1.2598, 2.4594],
        [2.5600, 1.4783, 1.7635, 2.6191, 2.0542]])



#### попробуем выключить подсчет градиентов у тензора b

In [86]:
a = torch.rand(3, 5, requires_grad = True)
b = torch.rand(3, 5, requires_grad = False)
a, b

(tensor([[0.1719, 0.9397, 0.4833, 0.1458, 0.3981],
         [0.8648, 0.3060, 0.4807, 0.8263, 0.1142],
         [0.5120, 0.8672, 0.1331, 0.8194, 0.3807]], requires_grad=True),
 tensor([[0.8651, 0.8863, 0.0581, 0.9480, 0.1203],
         [0.8373, 0.7147, 0.0968, 0.5830, 0.3923],
         [0.0896, 0.9237, 0.3895, 0.4250, 0.8848]]))

In [87]:
loss = torch.sum(a - b)

In [88]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [89]:
loss.backward()

In [90]:
print(f'{a.grad=}\n') # все единицы
print(f'{b.grad=}\n') # None

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=None



#### Попробуем выключать подсчет градиентов

In [1]:
import torch

In [2]:
a = torch.rand(3, 5, requires_grad = True)
b = torch.rand(3, 5, requires_grad = True)

a, b

(tensor([[0.6887, 0.6758, 0.4907, 0.9519, 0.5601],
         [0.6287, 0.8990, 0.6966, 0.2283, 0.6681],
         [0.1516, 0.5331, 0.7768, 0.7637, 0.4491]], requires_grad=True),
 tensor([[0.5524, 0.0844, 0.6616, 0.9538, 0.6013],
         [0.3998, 0.0108, 0.0082, 0.8993, 0.8181],
         [0.9719, 0.8694, 0.5145, 0.8076, 0.7984]], requires_grad=True))

In [3]:
with torch.no_grad():
    loss = torch.sum(a-b)

loss

tensor(0.2108)

In [4]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [5]:
# если мы создаем какие то тензоры внутри inference_mode - для них градиенты никогда не будут считаться
with torch.inference_mode():
    loss = torch.sum(a-b)
loss

tensor(0.2108)

In [6]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

#### Можно использовать в виде декоратора

In [7]:
@torch.no_grad()
def foo():
    a = torch.rand(3, 5, requires_grad = True)
    b = torch.rand(3, 5, requires_grad = True)
    loss = torch.mean(a - b)

    print(f'{loss=}')
    return a, b

In [8]:
a, b = foo()

loss=tensor(0.0617)


In [9]:
torch.mean(a - b) # есть grad_fn - можно считать градиенты

tensor(0.0617, grad_fn=<MeanBackward0>)

#### Сделаем то же самое с inference_mode

In [10]:
@torch.inference_mode()
def foo():
    a = torch.rand(3, 5, requires_grad = True)
    b = torch.rand(3, 5, requires_grad = True)
    loss = torch.mean(a - b)

    print(f'{loss=}')
    return a, b

In [11]:
a, b = foo()

loss=tensor(-0.0048)


In [12]:
torch.mean(a - b) # нет grad_fn - считать градиенты нельзя

tensor(-0.0048)

#### ! Что можно обернуть в inference_mode - функция предсказания, оценки качества (не обучаем - не считаем градиенты)
#### ! Это нужно для увеличения скорости работы

### Полносвязные слои и функции активации в ```Pytorch```

In [13]:
from torch import nn

In [15]:
layer = nn.Linear(in_features = 5, out_features = 3)
layer

Linear(in_features=5, out_features=3, bias=True)

In [17]:
layer.weight, layer.weight.shape

(Parameter containing:
 tensor([[-0.0427,  0.3468, -0.4333, -0.3353, -0.0787],
         [-0.1255, -0.1291,  0.0753,  0.2051,  0.0339],
         [ 0.3476,  0.0783, -0.0083,  0.3857,  0.1631]], requires_grad=True),
 torch.Size([3, 5]))

In [18]:
layer.bias

Parameter containing:
tensor([-0.4005, -0.3002, -0.1488], requires_grad=True)

In [19]:
# Пример
x = torch.rand(5)
layer(x)

tensor([-0.9246, -0.1603,  0.2945], grad_fn=<ViewBackward0>)

#### **Функции активации**

#### 1. Сигмоида

In [21]:
activation = nn.Sigmoid()

In [22]:
x = torch.rand(5)

print(x)

print(activation(x))

tensor([0.3301, 0.0211, 0.7228, 0.8888, 0.7560])
tensor([0.5818, 0.5053, 0.6732, 0.7086, 0.6805])


#### 2. ReLU

In [23]:
activation_relu = nn.ReLU()

In [29]:
x = torch.rand(5)
x[1] = -1
print(x)

print(activation_relu(x))

tensor([ 0.9326, -1.0000,  0.3658,  0.7127,  0.4576])
tensor([0.9326, 0.0000, 0.3658, 0.7127, 0.4576])


#### 3. Leaky ReLU

In [30]:
activation_leaky_relu = nn.LeakyReLU(negative_slope = 0.001)

In [31]:
x = torch.rand(5)
x[1] = -1
print(x)

print(activation_leaky_relu(x))

tensor([ 0.1773, -1.0000,  0.2411,  0.5872,  0.3129])
tensor([ 0.1773, -0.0100,  0.2411,  0.5872,  0.3129])


### **Градиентный спуск своими руками**

In [32]:
n_features = 2
n_objects = 300

torch.manual_seed(0)

w_true = torch.rand(n_features)
b_true = torch.rand(1)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.rand(n_objects) + b_true

In [33]:
n_steps = 200
step_size = 1e-2

In [36]:
w = torch.rand(n_features, requires_grad = True)
b = torch.rand(1, requires_grad = True)

for i in range(n_steps):
    y_pred = torch.matmul(x, w) + b

    mse = torch.mean((y_pred - y) ** 2)

    if i<20 or i%10 == 0:
        print(f'MSE на шаге {i} равен: {mse:.5f}')

    mse.backward()

    with torch.no_grad():
        w -= w.grad * step_size
        b -= b.grad * step_size

    w.grad.zero_()
    b.grad.zero_()

MSE на шаге 0 равен: 17.67167
MSE на шаге 1 равен: 6.02252
MSE на шаге 2 равен: 2.26013
MSE на шаге 3 равен: 0.99147
MSE на шаге 4 равен: 0.52832
MSE на шаге 5 равен: 0.33683
MSE на шаге 6 равен: 0.24452
MSE на шаге 7 равен: 0.19318
MSE на шаге 8 равен: 0.16155
MSE на шаге 9 равен: 0.14084
MSE на шаге 10 равен: 0.12681
MSE на шаге 11 равен: 0.11712
MSE на шаге 12 равен: 0.11033
MSE на шаге 13 равен: 0.10552
MSE на шаге 14 равен: 0.10206
MSE на шаге 15 равен: 0.09953
MSE на шаге 16 равен: 0.09764
MSE на шаге 17 равен: 0.09620
MSE на шаге 18 равен: 0.09507
MSE на шаге 19 равен: 0.09416
MSE на шаге 20 равен: 0.09341
MSE на шаге 30 равен: 0.08911
MSE на шаге 40 равен: 0.08663
MSE на шаге 50 равен: 0.08498
MSE на шаге 60 равен: 0.08387
MSE на шаге 70 равен: 0.08312
MSE на шаге 80 равен: 0.08262
MSE на шаге 90 равен: 0.08229
MSE на шаге 100 равен: 0.08206
MSE на шаге 110 равен: 0.08191
MSE на шаге 120 равен: 0.08181
MSE на шаге 130 равен: 0.08174
MSE на шаге 140 равен: 0.08169
MSE на шаге 15

In [39]:
layer = nn.Linear(in_features = n_features, out_features = 1)
for i in range(n_steps):
    y_pred = layer(x)

    mse = torch.mean((y_pred - y) ** 2)

    if i<20 or i%10 == 0:
        print(f'MSE на шаге {i} равен: {mse:.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size
    
    #layer.weight.grad.zero_()
    #layer.bias.grad.zero_()

    layer.zero_grad()

MSE на шаге 0 равен: 78.48883
MSE на шаге 1 равен: 58.30576
MSE на шаге 2 равен: 51.96949
MSE на шаге 3 равен: 49.95099
MSE на шаге 4 равен: 49.28663
MSE на шаге 5 равен: 49.05230
MSE на шаге 6 равен: 48.95820
MSE на шаге 7 равен: 48.91236
MSE на шаге 8 равен: 48.88482
MSE на шаге 9 равен: 48.86531
MSE на шаге 10 равен: 48.84997
MSE на шаге 11 равен: 48.83715
MSE на шаге 12 равен: 48.82602
MSE на шаге 13 равен: 48.81610
MSE на шаге 14 равен: 48.80708
MSE на шаге 15 равен: 48.79877
MSE на шаге 16 равен: 48.79101
MSE на шаге 17 равен: 48.78373
MSE на шаге 18 равен: 48.77683
MSE на шаге 19 равен: 48.77030
MSE на шаге 20 равен: 48.76406
MSE на шаге 30 равен: 48.71443
MSE на шаге 40 равен: 48.68129
MSE на шаге 50 равен: 48.65903
MSE на шаге 60 равен: 48.64410
MSE на шаге 70 равен: 48.63407
MSE на шаге 80 равен: 48.62733
MSE на шаге 90 равен: 48.62281
MSE на шаге 100 равен: 48.61978
MSE на шаге 110 равен: 48.61773
MSE на шаге 120 равен: 48.61637
MSE на шаге 130 равен: 48.61544
MSE на шаге 14

In [40]:
layer(x)

tensor([[0.0436],
        [0.0444],
        [0.0452],
        [0.0449],
        [0.0454],
        [0.0438],
        [0.0433],
        [0.0460],
        [0.0427],
        [0.0455],
        [0.0453],
        [0.0425],
        [0.0438],
        [0.0443],
        [0.0463],
        [0.0446],
        [0.0437],
        [0.0443],
        [0.0445],
        [0.0429],
        [0.0440],
        [0.0421],
        [0.0456],
        [0.0427],
        [0.0446],
        [0.0429],
        [0.0428],
        [0.0442],
        [0.0424],
        [0.0456],
        [0.0434],
        [0.0437],
        [0.0432],
        [0.0467],
        [0.0427],
        [0.0435],
        [0.0448],
        [0.0426],
        [0.0448],
        [0.0438],
        [0.0422],
        [0.0440],
        [0.0426],
        [0.0425],
        [0.0434],
        [0.0463],
        [0.0422],
        [0.0457],
        [0.0415],
        [0.0457],
        [0.0453],
        [0.0453],
        [0.0430],
        [0.0449],
        [0.0459],
        [0

In [41]:
layer(x).shape

torch.Size([300, 1])

In [42]:
(layer(x) - y).shape

torch.Size([300, 300])

In [43]:
n_features = 2
n_objects = 300

torch.manual_seed(0)

w_true = torch.rand(n_features)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.rand(n_objects) + b_true

In [44]:
layer = nn.Linear(in_features = n_features, out_features = 1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i} равен: {mse:.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 0 равен: 6.85275
MSE на шаге 1 равен: 2.23049
MSE на шаге 2 равен: 0.79783
MSE на шаге 3 равен: 0.34386
MSE на шаге 4 равен: 0.19329
MSE на шаге 5 равен: 0.13889
MSE на шаге 6 равен: 0.11638
MSE на шаге 7 равен: 0.10540
MSE на шаге 8 равен: 0.09916
MSE на шаге 9 равен: 0.09523
MSE на шаге 10 равен: 0.09258
MSE на шаге 11 равен: 0.09074
MSE на шаге 12 равен: 0.08942
MSE на шаге 13 равен: 0.08845
MSE на шаге 14 равен: 0.08772
MSE на шаге 15 равен: 0.08717
MSE на шаге 16 равен: 0.08673
MSE на шаге 17 равен: 0.08637
MSE на шаге 18 равен: 0.08607
MSE на шаге 19 равен: 0.08581
MSE на шаге 50 равен: 0.08251
MSE на шаге 100 равен: 0.08139
MSE на шаге 150 равен: 0.08124


#### Сделаем для 5 признаков

In [53]:
n_steps = 2000
step_size = 1e-3

In [54]:
n_features = 5
n_objects = 300

torch.manual_seed(0)

w_true = torch.rand(n_features)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.rand(n_objects) + b_true

In [55]:
layer = nn.Linear(in_features = n_features, out_features = 1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i} равен: {mse:.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 0 равен: 140.48267
MSE на шаге 1 равен: 68.83474
MSE на шаге 2 равен: 46.60955
MSE на шаге 3 равен: 32.99631
MSE на шаге 4 равен: 23.77119
MSE на шаге 5 равен: 17.31469
MSE на шаге 6 равен: 12.73444
MSE на шаге 7 равен: 9.46603
MSE на шаге 8 равен: 7.12717
MSE на шаге 9 равен: 5.45065
MSE на шаге 10 равен: 4.24719
MSE на шаге 11 равен: 3.38196
MSE на шаге 12 равен: 2.75868
MSE на шаге 13 равен: 2.30853
MSE на шаге 14 равен: 1.98231
MSE на шаге 15 равен: 1.74485
MSE на шаге 16 равен: 1.57097
MSE на шаге 17 равен: 1.44269
MSE на шаге 18 равен: 1.34711
MSE на шаге 19 равен: 1.27504
MSE на шаге 50 равен: 0.83768
MSE на шаге 100 равен: 0.63470
MSE на шаге 150 равен: 0.52351
MSE на шаге 200 равен: 0.44153
MSE на шаге 250 равен: 0.37576
MSE на шаге 300 равен: 0.32199
MSE на шаге 350 равен: 0.27786
MSE на шаге 400 равен: 0.24162
MSE на шаге 450 равен: 0.21184
MSE на шаге 500 равен: 0.18738
MSE на шаге 550 равен: 0.16728
MSE на шаге 600 равен: 0.15077
MSE на шаге 650 равен: 0.13721


#### Сделаем 2 полносвязных слоя с функцией активации ReLU

In [62]:
n_steps = 2000
step_size = 1e-3

In [63]:
layer1 = nn.Linear(in_features = n_features, out_features = 3)
layer2 = nn.Linear(in_features = 3, out_features = 1)
activation = nn.ReLU()

for i in range(n_steps):
    y_pred = layer2(activation(layer1(x))).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i} равен: {mse:.5f}')

    mse.backward()

    with torch.no_grad():
        layer1.weight -= layer1.weight.grad * step_size
        layer1.bias -= layer1.bias.grad * step_size
        layer2.weight -= layer2.weight.grad * step_size
        layer2.bias -= layer2.bias.grad * step_size

    layer1.zero_grad()
    layer2.zero_grad()
    

MSE на шаге 0 равен: 119.35091
MSE на шаге 1 равен: 107.98933
MSE на шаге 2 равен: 100.38038
MSE на шаге 3 равен: 93.93559
MSE на шаге 4 равен: 87.53906
MSE на шаге 5 равен: 81.08051
MSE на шаге 6 равен: 74.50467
MSE на шаге 7 равен: 67.79933
MSE на шаге 8 равен: 61.42850
MSE на шаге 9 равен: 55.69221
MSE на шаге 10 равен: 50.78044
MSE на шаге 11 равен: 46.68363
MSE на шаге 12 равен: 43.29419
MSE на шаге 13 равен: 40.43761
MSE на шаге 14 равен: 37.88225
MSE на шаге 15 равен: 35.57067
MSE на шаге 16 равен: 33.44225
MSE на шаге 17 равен: 31.47860
MSE на шаге 18 равен: 29.61618
MSE на шаге 19 равен: 27.87950
MSE на шаге 50 равен: 6.74872
MSE на шаге 100 равен: 1.49023
MSE на шаге 150 равен: 0.90103
MSE на шаге 200 равен: 0.57924
MSE на шаге 250 равен: 0.38943
MSE на шаге 300 равен: 0.26975
MSE на шаге 350 равен: 0.19914
MSE на шаге 400 равен: 0.16124
MSE на шаге 450 равен: 0.14042
MSE на шаге 500 равен: 0.12780
MSE на шаге 550 равен: 0.11976
MSE на шаге 600 равен: 0.11408
MSE на шаге 650 